// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProAgil.WebAPI.Data;

namespace ProAgil.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("ProAgil.WebAPI.Model.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DataEvento")
                        .HasColumnType("longtext");

                    b.Property<string>("Local")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Lote")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("QtdPessoas")
                        .HasColumnType("int");

                    b.Property<string>("Tema")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("EventoId");

                    b.ToTable("Eventos");

                    b.HasData(
                        new
                        {
                            EventoId = 1,
                            DataEvento = "29/08/2021 23:50:42",
                            Local = "Belo Horizonte",
                            Lote = "1° Lote",
                            QtdPessoas = 255,
                            Tema = "ANGULAR + ASPNET CORE 5"
                        },
                        new
                        {
                            EventoId = 2,
                            DataEvento = "01/09/2021 23:50:42",
                            Local = "Belo Horizonte",
                            Lote = "2° Lote",
                            QtdPessoas = 255,
                            Tema = "ANGULAR + ASPNET CORE 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
